exports.BASE_URL = 'http://localhost:3000'
exports.GET_ALL_ITEMS = '/api/list/getAll'
exports.GET_ITEM = '/api/list/getItem'
exports.GET_FARMS = '/api/list/getFarms'
exports.GET_RECENT_ITEMS = '/api/list/getRecent'
exports.ADD_ITEM = '/api/list/addItem'
exports.SIGN_UP = '/api/auth/signup'
