// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ll6E_WSyK0Mtw4iZkWTRseXtk3uoJp8',
    appId: '1:409014648530:web:1704ff16360da2dfc0f70b',
    messagingSenderId: '409014648530',
    projectId: 'freshnet-a4948',
    authDomain: 'freshnet-a4948.firebaseapp.com',
    storageBucket: 'freshnet-a4948.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqhHLd-fB-4zypgu5jpJlgLfiUBECgFzI',
    appId: '1:409014648530:android:40a0869736d1f4dcc0f70b',
    messagingSenderId: '409014648530',
    projectId: 'freshnet-a4948',
    storageBucket: 'freshnet-a4948.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmkZCTfSDxXMyp9rvUR15ajxq3Id4tSic',
    appId: '1:409014648530:ios:e98b208a650c91ecc0f70b',
    messagingSenderId: '409014648530',
    projectId: 'freshnet-a4948',
    storageBucket: 'freshnet-a4948.appspot.com',
    iosBundleId: 'com.example.agroMillets',
  );
}
